#!/system/bin/sh
# ============================================================
# DNSCrypt Smart Filter – watchdog.sh
# Version: v1.2.0 (Global Edition)
# Author: gasciljh
# Repository: https://github.com/gasciljh/dnscrypt-proxy-webui
# ============================================================
# Purpose:
#   Standalone watchdog process that monitors the WebUI and the
#   DNS Engine and restarts them when needed.
#
#   The watchdog is launched by service.sh as an independent
#   process (nohup + background), so that $$ inside this file
#   refers to the real watchdog PID, not service.sh's.
#
# Responsibilities:
#   • Monitor the WebUI (TCP port) and restart it if closed
#   • Monitor the DNS Engine (5354/UDP) and restart it via the
#     main.go API (POST /api/ensure_running_service)
#   • Respect STATUS_FILE as "user intent":
#       ON  → restart DNS if crashed
#       OFF → do nothing (user stopped it manually)
#   • Exponential backoff (30s → 600s max) per service
#   • Reset backoff on success and on STATUS_FILE change
#   • Handle HTTP 429 (rate limit) with additional backoff
#   • Exit cleanly when the disable file is present
#
# Arguments (in order):
#   1. WATCHDOG_PID_FILE   — path to the watchdog PID file
#   2. MODDIR              — module directory
#   3. PORT                — WebUI port (TCP)
#   4. AUTO_RESTART_DNS    — "0" or "1"
#   5. AUTO_RESTART_WEBUI  — "0" or "1"
#
# Authentication (v1.2.0 — Global Edition):
#   watchdog_api_call() authenticates to
#   POST /api/ensure_running_service using, in order of
#   preference:
#
#     1. X-Watchdog-Token header  ← preferred
#        The token is generated by:
#          • customize.sh  §[19b] (during install), or
#          • main.go       loadOrCreateWatchdogToken() (first
#                           WebUI startup, if the installer
#                           did not create one).
#        It is read from: $RUN_DIR/.watchdog_token (mode 0600).
#
#     2. Authorization: Basic <user:pass>  ← fallback
#        Read from [monitoring_ui] in dnscrypt-proxy.toml.
#        Used only when the token file is missing or empty.
#
#   The token path is preferred because it is:
#     • Independent of the credentials file.
#     • Constant-time-compared in main.go (subtle.ConstantTimeCompare).
#     • Localhost-scoped (main.go still checks isLocalRequest).
#     • Not subject to the login rate limiter (5 attempts / 15 min).
#
# API call:
#   Uses POST /api/ensure_running_service (CSRF-GET protection).
#   Return codes:
#     0 — success (2xx)
#     1 — no HTTP client available
#     2 — network/timeout failure
#     3 — 429 rate-limited
#     4 — other HTTP error, OR unable to determine the result
#
# v1.1.0 additions (kept):
#   • Logs the active profile + expected memory hint at startup
#     (self-contained — does not depend on functions.sh)
#   • Structured startup banner with profile context
#   • All messages are English (global release)
#
# v1.2.0 additions:
#   • Watchdog token authentication (see above).
#   • Explicit note: this script does NOT participate in the
#     v1.2.0 data-preservation layers. Its sole responsibility
#     is restarting services.
#   • Startup diagnostics block ([5b]) that logs (read-only):
#       - Number of available snapshots
#       - Content of .last_stable
#       - Content of .pending_notification (if any)
#       - Number of in-flight + orphan transaction dirs
#   • Shutdown messages distinguish SIGTERM, SIGINT, SIGQUIT.
#   • Startup banner is structured into sections
#     (Config / Paths / Auth / Data Preservation).
#   • All messages are English-only (global edition).
#
# ============================================================
# v1.2.0 — POST-AUDIT FIXES, ROUND 1 (kept)
# ============================================================
# A pre-release audit of this file identified the following
# issues. All of them are addressed in-place; no version bump.
#
#   🔧 BUG-A (critical) — The `watchdog_api_call` function wrote
#     curl's HTTP status code to a file under `/tmp/`. On modern
#     Android, `/tmp` is NOT guaranteed to exist. When the
#     redirect failed, `http_code` stayed empty and the function
#     fell through to "success" — defeating the watchdog's
#     primary purpose.
#
#     Fix: all temporary files now live under `$RUN_DIR`.
#
#   🔧 BUG-B — An empty `http_code` was still treated as
#     success. This is undecidable: it can mean a truncated
#     response, a proxy injecting garbage, or an ancient curl
#     that does not support -w.
#
#     Fix: return 4 (other HTTP error) when http_code is empty.
#
#   🔧 BUG-C — `PORT` was only checked for emptiness. A
#     non-numeric value would cause an infinite restart loop.
#
#     Fix: validate PORT is a positive integer in [1, 65535];
#     fall back to 9090 otherwise.
#
#   🔧 WD-1 — A `{ ... } 2>/dev/null` block around the profile
#     memory hint call was a no-op. Removed.
#
#   🔧 WD-2 — The comment above the backoff constants said
#     "Reset when STATUS_FILE changes" without qualifying that
#     this applies ONLY to DNS_BACKOFF_CURRENT. Clarified.
#
#   🔧 WD-3 — Argument validation only checked $1 and $2.
#     Now it also validates the total argument count and the
#     numeric nature of $3 (PORT).
#
#   🔧 WD-TOKEN (critical) — Watchdog now sends
#     the X-Watchdog-Token header. See the "Authentication"
#     block above for the full server-side contract.
#
# ============================================================
# v1.2.0 — POST-AUDIT FIXES, ROUND 2 (this revision)
# ============================================================
# A second independent audit of this file identified the
# following issues. All are fixed in-place; no version bump.
#
#   🔧 M-4 (CRITICAL) — The wget/busybox fallback paths in
#     `watchdog_api_call` used `-qO-`, which does NOT print
#     HTTP response headers. As a result, `http_code` was
#     ALWAYS empty in those paths, and the BUG-B fix (empty
#     code → return 4) turned every SUCCESSFUL restart over
#     wget/busybox into a "failure". This caused an infinite
#     retry loop with growing backoff — precisely on the
#     ancient devices where curl is missing.
#
#     Fix: for wget/busybox, rely on the process exit code:
#       • 0 → 2xx success
#       • 8 → HTTP error (GNU wget only) → return 4
#       • any other non-zero → network/timeout → return 2
#     A 429 cannot be distinguished in this path; it will be
#     treated as a generic failure (return 2 or 4), which is
#     acceptable because the backoff is applied anyway.
#
#   🔧 M-2 — `_wd_cleanup_webui` was called TWICE when
#     restarting the WebUI: once in section [13.2] and once
#     inside `_wd_start_webui`. The inner call has been
#     removed; `_wd_start_webui` now documents the
#     precondition that no prior instance must be running.
#
#   🔧 M-3 — `wd_token=$(_wd_get_watchdog_token 2>/dev/null
#     || echo "")` was over-defensive. The helper writes
#     nothing to stderr, and its failure mode is "empty
#     stdout", not a non-zero exit that aborts the caller.
#     Simplified to `|| :` (explicit no-op) for readability.
#
#   🔧 M-5 / M-6 — Section [5b] duplicated the token-
#     validation logic instead of reusing
#     `_wd_get_watchdog_token`. Any future change to the token
#     contract would have required editing two places. The
#     helper has been MOVED to section [2b] (before [3]) so it
#     is available to [5b], and [5b] now calls it.
#
#   🔧 M-1 — The case pattern `sh|ash|bash|busybox|*sh` was
#     redundant: `*sh` already covers sh/ash/bash. Collapsed
#     to `busybox|*sh`.
#
#   🔧 L-1 / L-2 — The argument-count check accepted
#     `$# >= 5` and silently ignored extra arguments. It now
#     requires EXACTLY 5 arguments, and the error message has
#     been reworded accordingly.
#
#   🔧 L-3 — The duplicate-instance guard used `kill -0`,
#     which returns 0 for zombie processes. A zombie watchdog
#     from a previous boot could therefore block the new
#     instance forever. The guard now also inspects
#     /proc/PID/stat and treats state 'Z' as "not running".
#
# ============================================================
# Coordination with v1.2.0 data-preservation layers:
# ============================================================
#   watchdog.sh does NOT participate in any of the layers
#   listed below. It runs continuously in the background and
#   only restarts the WebUI / DNS engine when they become
#   unavailable.
#
#   The persistent backup directory is never touched by this
#   script — even when services restart (which is the normal
#   behaviour of a watchdog and not a data-critical event).
#
#   The startup diagnostics block ([5b]) is READ-ONLY.
#
#   Layer table:
#     1  — Multi-source detection   — customize.sh
#     2  — Persistent backup        — service.sh + main.go
#     3  — Integrity verification   — customize.sh
#     4  — Transactional upgrades   — customize.sh
#     5  — Root-solution compat     — customize.sh
#     6  — SELinux preservation     — customize.sh
#     7  — Recovery mode            — customize.sh
#     8  — Config migrations        — customize.sh
#     9  — Automation + rotation    — service.sh
#     10 — Observability            — status.sh --diagnose
#
# ============================================================
# POSIX note on `local`:
#   This script uses `local` for all internal variables. The
#   `local` keyword is supported by:
#     • mksh (the default /system/bin/sh on modern Android)
#     • busybox ash (older Android)
#     • bash, dash, ksh
#   It is NOT part of the POSIX sh standard, but every shell
#   Android ships supports it.
# ============================================================

# v1.2.0: --version flag (checked before any argument parsing)
case "${1:-}" in
	--version)
		echo "$0: v1.2.0"
		exit 0
		;;
esac

export PATH=/sbin:/system/bin:/system/xbin:/vendor/bin:/data/adb/magisk:/data/adb/ksu/bin:/data/adb/ap/bin:$PATH

# ============================================================
# [1] Parse arguments
# ============================================================
# L-1 / L-2 fix: require EXACTLY 5 arguments. Fewer means the
# caller is broken; more means the caller expects an interface
# that does not exist. In both cases, fail fast with a clear
# message rather than silently ignoring the extras.
if [ "$#" -ne 5 ]; then
    echo "watchdog.sh: requires exactly 5 arguments, got $#" >&2
    echo "Usage: watchdog.sh <pid_file> <moddir> <port> <auto_dns> <auto_webui>" >&2
    exit 1
fi

WATCHDOG_PID_FILE="$1"
MODDIR="$2"
PORT="$3"
AUTO_RESTART_DNS="$4"
AUTO_RESTART_WEBUI="$5"

# --- Validate required args ---
if [ -z "$WATCHDOG_PID_FILE" ] || [ -z "$MODDIR" ]; then
    echo "watchdog.sh: missing required args" >&2
    echo "Usage: watchdog.sh <pid_file> <moddir> <port> <auto_dns> <auto_webui>" >&2
    exit 1
fi

if [ ! -d "$MODDIR" ]; then
    echo "watchdog.sh: MODDIR not found: $MODDIR" >&2
    exit 1
fi

# --- BUG-C fix: validate PORT is a positive integer ---
if ! echo "$PORT" | grep -qE '^[0-9]+$' || [ "$PORT" -lt 1 ] || [ "$PORT" -gt 65535 ]; then
    PORT="9090"
fi

[ -z "$AUTO_RESTART_DNS" ]   && AUTO_RESTART_DNS="1"
[ -z "$AUTO_RESTART_WEBUI" ] && AUTO_RESTART_WEBUI="1"

case "$AUTO_RESTART_DNS"   in 0|1) ;; *) AUTO_RESTART_DNS="1"   ;; esac
case "$AUTO_RESTART_WEBUI" in 0|1) ;; *) AUTO_RESTART_WEBUI="1" ;; esac

# --- Validate WEBUI binary ---
WEBUI="$MODDIR/proxy/dnscrypt-webui"
if [ ! -f "$WEBUI" ]; then
    echo "watchdog.sh: WEBUI binary not found: $WEBUI" >&2
    exit 1
fi

# ============================================================
# [2] Paths
# ============================================================
LOG_FILE="/data/local/tmp/dnscrypt_main.log"
RUN_DIR="$MODDIR/proxy/run"
STATUS_FILE="$RUN_DIR/dnscrypt.status"
TOML_FILE="$MODDIR/proxy/dnscrypt-proxy.toml"
SELECTED_PROFILE_FILE="$MODDIR/proxy/selected_profile.txt"

# --- v1.2.0 — Watchdog token (WD-TOKEN fix) ---
WATCHDOG_TOKEN_FILE="$RUN_DIR/.watchdog_token"

# --- v1.2.0 — Data preservation paths (READ-ONLY access) ---
PERSISTENT_BACKUP="/sdcard/dnscrypt-webui-backup"
LAST_STABLE_FILE="$PERSISTENT_BACKUP/.last_stable"
PENDING_NOTIFY_FILE="$PERSISTENT_BACKUP/.pending_notification"
USER_FILES="webui.conf dnscrypt-proxy.toml selected_profile.txt allowlist.txt denylist.txt"

# Fallback if run/ is not writable
if [ ! -d "$RUN_DIR" ] || [ ! -w "$RUN_DIR" ]; then
    RUN_DIR="/data/local/tmp"
    STATUS_FILE="/data/local/tmp/dnscrypt.status"
    WATCHDOG_TOKEN_FILE="/data/local/tmp/.watchdog_token"
fi

# ============================================================
# [2b] Watchdog token reader (WD-TOKEN / M-5 / M-6 fix)
# ============================================================
# MOVED HERE (previously section [7b]) so that section [5b]
# can reuse it instead of duplicating the validation logic.
#
# Reads the token file written by customize.sh §[19b] (during
# install) or by main.go loadOrCreateWatchdogToken() (first
# WebUI startup). The token is sent as the X-Watchdog-Token
# header in `watchdog_api_call`.
#
# File location:
#   $RUN_DIR/.watchdog_token  (mode 0600, 64 hex chars)
#
# The token is re-read on EVERY API call (not cached) because:
#   • Reads are cheap (one file, 64 bytes).
#   • main.go may regenerate the token if the file is missing
#     on first startup — a cached empty value would then stay
#     empty forever.
#   • A rotated token (unlikely but possible) is picked up
#     without a watchdog restart.
#
# Return values:
#   0 — token read and looks valid (>= 32 chars); printed to stdout
#   1 — token file missing, empty, or too short
#
# This helper is deliberately self-contained (not sourced from
# functions.sh) because watchdog.sh must run even when
# functions.sh is missing or unreadable.
# ============================================================
_wd_get_watchdog_token() {
    [ -f "$WATCHDOG_TOKEN_FILE" ] || return 1

    local tok
    tok=$(cat "$WATCHDOG_TOKEN_FILE" 2>/dev/null | tr -d '\r\n ')

    [ -n "$tok" ] || return 1
    [ "${#tok}" -ge 32 ] || return 1

    printf "%s" "$tok"
    return 0
}

# ============================================================
# [3] log_msg
# ============================================================
# HARD-WD-03: emergency-only rotation at 50 MB, every 100th
# call. Mirrors functions.sh:log_fn. The counter is a global
# by design (it must persist across calls).
_LOG_CALL_COUNT=0

log_msg() {
    _LOG_CALL_COUNT=$((_LOG_CALL_COUNT + 1))

    if [ $((_LOG_CALL_COUNT % 100)) -eq 0 ] && [ -f "$LOG_FILE" ]; then
        local _size
        _size=$(wc -c < "$LOG_FILE" 2>/dev/null | tr -d ' ')
        if [ -n "$_size" ] && [ "$_size" -gt 52428800 ]; then
            local _emg="${LOG_FILE}.emergency.$(date +%s)"
            mv -f "$LOG_FILE" "$_emg" 2>/dev/null
            : > "$LOG_FILE"
        fi
    fi

    echo "$(date +'%Y-%m-%d %H:%M:%S') - [watchdog] $1" >> "$LOG_FILE" 2>/dev/null
}

# ============================================================
# [4] Prevent duplicate watchdog instances
# ============================================================
# M-1 fix: `*sh` already matches sh/ash/bash; only busybox
# needs an explicit alternative. The pattern list has been
# collapsed for clarity.
#
# L-3 fix: `kill -0` returns 0 for zombies. A zombie watchdog
# from a previous boot would block the new instance forever.
# We now also inspect /proc/PID/stat and reject state 'Z'.
# ============================================================
if [ -f "$WATCHDOG_PID_FILE" ]; then
    old_pid=$(cat "$WATCHDOG_PID_FILE" 2>/dev/null | tr -d '\r\n ')
    if [ -n "$old_pid" ] && [ -d "/proc/$old_pid" ]; then
        # L-3: reject zombies. awk is safe here because `comm`
        # for shell processes never contains spaces (the kernel
        # truncates it to 15 chars and replaces problematic
        # characters).
        old_state=$(awk '{print $3}' "/proc/$old_pid/stat" 2>/dev/null)

        if [ "$old_state" = "Z" ]; then
            log_msg "PID $old_pid is a zombie (stale PID file) — ignoring"
        else
            old_comm=$(cat "/proc/$old_pid/comm" 2>/dev/null)
            case "$old_comm" in
                busybox|*sh)
                    log_msg "Watchdog already running (PID: $old_pid), exiting"
                    exit 0
                    ;;
                *)
                    log_msg "PID $old_pid was reused by '$old_comm', ignoring"
                    ;;
            esac
        fi
    fi
fi

# ============================================================
# [5] Write real PID
# ============================================================
# We run as an independent process (not a subshell).
# $$ = this process's PID = real watchdog PID.
#
# HARD-WD-04: explicit error check. A failed write would leave
# the script running without a PID file, defeating the
# duplicate-instance guard in section [4] on the next boot.
# ============================================================
if ! printf "%d\n" $$ > "${WATCHDOG_PID_FILE}.tmp" 2>/dev/null; then
    log_msg "FATAL: cannot write PID tmp file: ${WATCHDOG_PID_FILE}.tmp"
    exit 1
fi
if ! mv -f "${WATCHDOG_PID_FILE}.tmp" "$WATCHDOG_PID_FILE" 2>/dev/null; then
    log_msg "FATAL: cannot move PID file into place: $WATCHDOG_PID_FILE"
    rm -f "${WATCHDOG_PID_FILE}.tmp" 2>/dev/null
    exit 1
fi

# ============================================================
# [5b] v1.2.0 — Startup diagnostics (READ-ONLY)
# ============================================================
# Logs a structured snapshot of the module state at watchdog
# startup. This makes the boot log a complete picture without
# requiring the user to run status.sh manually.
#
# ⚠️ READ-ONLY: This block inspects the backup directory but
#    does NOT create, modify, or delete any files.
# ============================================================

# --- Read pending notification (if any) ---
_pending_msg=""
if [ -f "$PENDING_NOTIFY_FILE" ]; then
    _pending_msg=$(cat "$PENDING_NOTIFY_FILE" 2>/dev/null | tr -d '\r\n ')
fi

# --- Read .last_stable (if any) ---
_last_stable=""
if [ -f "$LAST_STABLE_FILE" ]; then
    _last_stable=$(cat "$LAST_STABLE_FILE" 2>/dev/null | tr -d '\r\n ')
fi

# --- Count available snapshots ---
_snap_count=0
if [ -d "$PERSISTENT_BACKUP" ]; then
    _snap_count=$(cd "$PERSISTENT_BACKUP" 2>/dev/null && \
        ls -1d */ 2>/dev/null | \
        sed 's:/$::' | \
        grep -E '^[0-9]{8}-[0-9]{6}-' | \
        wc -l | tr -d ' ')
    [ -z "$_snap_count" ] && _snap_count=0
fi

# --- Count in-flight transactions (txn-*) ---
_txn_count=0
if [ -d "$PERSISTENT_BACKUP" ]; then
    _txn_count=$(cd "$PERSISTENT_BACKUP" 2>/dev/null && \
        ls -1d txn-*/ 2>/dev/null | \
        wc -l | tr -d ' ')
    [ -z "$_txn_count" ] && _txn_count=0
fi

# --- Count orphan transactions (orphan-txn-*) ---
_orphan_count=0
if [ -d "$PERSISTENT_BACKUP" ]; then
    _orphan_count=$(cd "$PERSISTENT_BACKUP" 2>/dev/null && \
        ls -1d orphan-txn-*/ 2>/dev/null | \
        wc -l | tr -d ' ')
    [ -z "$_orphan_count" ] && _orphan_count=0
fi

# --- Check whether the watchdog token file exists ---
# M-5 / M-6 fix: delegate to the canonical helper instead of
# duplicating the ">= 32 chars" validation here. A single
# source of truth for the token contract.
_token_present="no"
if _wd_get_watchdog_token >/dev/null 2>&1; then
    _token_present="yes"
fi

# ============================================================
# [5c] Startup banner (structured)
# ============================================================
log_msg "============================================"
log_msg "Watchdog started (PID: $$)"
log_msg "   Version: v1.2.0 (Global Edition)"
log_msg "─── Config ───"
log_msg "   MODDIR:     $MODDIR"
log_msg "   PORT:       $PORT"
log_msg "   Auto-DNS:   $AUTO_RESTART_DNS"
log_msg "   Auto-WebUI: $AUTO_RESTART_WEBUI"
log_msg "─── Paths ───"
log_msg "   RUN_DIR:    $RUN_DIR"
log_msg "   STATUS_FILE: $STATUS_FILE"
log_msg "─── Auth ───"
log_msg "   Token file: $WATCHDOG_TOKEN_FILE"
log_msg "   Token ready: $_token_present"
log_msg "─── Data Preservation (READ-ONLY) ───"
log_msg "   Snapshot dir:   $PERSISTENT_BACKUP"
log_msg "   Snapshots:      $_snap_count"
log_msg "   In-flight txn:  $_txn_count"
log_msg "   Orphan txn:     $_orphan_count"
if [ -n "$_last_stable" ]; then
    log_msg "   Last stable:    $_last_stable"
else
    log_msg "   Last stable:    (none yet)"
fi
if [ -n "$_pending_msg" ]; then
    log_msg "   Notification:   $_pending_msg"
    log_msg "   (main.go will log and delete this at startup)"
fi
log_msg "   Note: this script does NOT touch the backup directory."
log_msg "============================================"

# ============================================================
# [6] Trap for clean exit
# ============================================================
# Three separate traps so the log clearly distinguishes which
# signal caused the exit.
#
# The shellcheck SC2064 directive is required because the trap
# strings deliberately use single quotes so that $$ and
# $WATCHDOG_PID_FILE are expanded at FIRE time, not at
# set-up time.
# ============================================================
# shellcheck disable=SC2064
trap '
    log_msg "Watchdog terminated (SIGTERM)";
    rm -f "$WATCHDOG_PID_FILE" 2>/dev/null;
    exit 0
' TERM

# shellcheck disable=SC2064
trap '
    log_msg "Watchdog terminated (SIGINT)";
    rm -f "$WATCHDOG_PID_FILE" 2>/dev/null;
    exit 0
' INT

# shellcheck disable=SC2064
trap '
    log_msg "Watchdog terminated (SIGQUIT)";
    rm -f "$WATCHDOG_PID_FILE" 2>/dev/null;
    exit 0
' QUIT

# ============================================================
# [7] Internal helpers (self-contained — no functions.sh dependency)
# ============================================================

# --- Port check ---
# HARD-WD-02: added `netstat` fallback for older Android builds
# that ship without `ss`.
_wd_is_port_open() {
    local port="$1"
    local proto="${2:-tcp}"
    local hex_port

    case "$port" in
        ''|*[!0-9]*) return 1 ;;
    esac

    hex_port=$(printf "%04X" "$port" 2>/dev/null) || return 1

    if [ "$proto" = "udp" ]; then
        if [ -f /proc/net/udp ] && grep -qi ":$hex_port " /proc/net/udp 2>/dev/null; then
            return 0
        fi
        if [ -f /proc/net/udp6 ] && grep -qi ":$hex_port " /proc/net/udp6 2>/dev/null; then
            return 0
        fi
        if command -v ss >/dev/null 2>&1; then
            ss -lun 2>/dev/null | grep -q ":$port " && return 0
        elif command -v netstat >/dev/null 2>&1; then
            netstat -uln 2>/dev/null | grep -q ":$port " && return 0
        fi
    else
        if [ -f /proc/net/tcp ] && grep -qi ":$hex_port " /proc/net/tcp 2>/dev/null; then
            return 0
        fi
        if [ -f /proc/net/tcp6 ] && grep -qi ":$hex_port " /proc/net/tcp6 2>/dev/null; then
            return 0
        fi
        if command -v ss >/dev/null 2>&1; then
            ss -ltn 2>/dev/null | grep -q ":$port " && return 0
        elif command -v netstat >/dev/null 2>&1; then
            netstat -tln 2>/dev/null | grep -q ":$port " && return 0
        fi
    fi

    return 1
}

# --- WebUI cleanup ---
_wd_cleanup_webui() {
    pkill -9 -x dnscrypt-webui 2>/dev/null
    rm -f "$RUN_DIR/webui.pid" 2>/dev/null
    rm -f /data/local/tmp/webui.pid 2>/dev/null
}

# --- Start WebUI ---
# ⚠️ PRECONDITION (M-2 fix): the caller MUST have already
# ensured that no previous WebUI instance is running. The
# canonical way to do so is `_wd_cleanup_webui`. This function
# deliberately does NOT call it, so that its side effects
# (kill -9, PID-file removal) remain visible at the call site
# in section [13.2] and are not hidden inside a "start" helper.
_wd_start_webui() {
    local bin="$1"
    local port="$2"

    log_msg "Starting WebUI (port: $port)"

    export HOME=/data/local/tmp

    if command -v setsid >/dev/null 2>&1; then
        setsid env HOME="$HOME" "$bin" >/dev/null 2>&1 < /dev/null &
    elif command -v busybox >/dev/null 2>&1 && busybox --list 2>/dev/null | grep -q setsid; then
        busybox setsid env HOME="$HOME" "$bin" >/dev/null 2>&1 < /dev/null &
    else
        nohup env HOME="$HOME" "$bin" >/dev/null 2>&1 < /dev/null &
    fi

    sleep 1
    local web_pid=""
    web_pid=$(pgrep -x "dnscrypt-webui" 2>/dev/null | head -n1)

    if [ -n "$web_pid" ]; then
        printf "%d\n" "$web_pid" > "${RUN_DIR}/webui.pid.tmp" 2>/dev/null
        mv -f "${RUN_DIR}/webui.pid.tmp" "${RUN_DIR}/webui.pid" 2>/dev/null
    fi

    local i=0
    while [ "$i" -lt 35 ]; do
        if [ -n "$web_pid" ] && ! kill -0 "$web_pid" 2>/dev/null; then
            log_msg "ERROR: WebUI process died (Port collision?)"
            return 1
        fi
        if _wd_is_port_open "$port" tcp; then
            log_msg "WebUI bound to port $port (PID: ${web_pid:-unknown})"
            return 0
        fi
        sleep 1
        i=$((i + 1))
    done

    log_msg "ERROR: WebUI failed to bind within 35s"
    return 1
}

# --- Read profile memory hint (v1.1.0, self-contained) ---
#
# Returns a user-facing string describing the expected soft
# memory limit for the active profile.
#
# ⚠️ This is a HINT only. main.go is the authority.
#
# Uses the same table as:
#   • functions.sh:get_profile_memory_hint
#   • main.go:memoryLimitForProfile
#   • customize.sh [21]
#
# Table:
#   light    →  80 MB
#   normal   → 100 MB
#   pro      → 120 MB
#   proplus  → 160 MB
#   ultimate → 220 MB
_wd_get_profile_memory_hint() {
    local profile="pro"

    if [ -f "$SELECTED_PROFILE_FILE" ]; then
        local p
        p=$(cat "$SELECTED_PROFILE_FILE" 2>/dev/null | tr -d '\r\n ')
        case "$p" in
            light|normal|pro|proplus|ultimate) profile="$p" ;;
        esac
    fi

    local mb
    case "$profile" in
        light)    mb="80"  ;;
        normal)   mb="100" ;;
        pro)      mb="120" ;;
        proplus)  mb="160" ;;
        ultimate) mb="220" ;;
        *)        mb="80"  ;;
    esac

    printf "%s MB (%s)" "$mb" "$profile"
}

# ============================================================
# [8] Read credentials — section-restricted (fallback auth)
# ============================================================
# Reads ONLY from [monitoring_ui]. Section tracking ignores any
# username/password in other sections.
#
# This is used ONLY as a fallback when the watchdog token file
# is not available (see WD-TOKEN fix). With the token file in
# place, the Basic Auth header is not sent.
# ============================================================
WATCH_USER=""
WATCH_PASS=""
HAS_CREDS=0

if [ -f "$TOML_FILE" ]; then
    in_section=0
    while IFS= read -r line || [ -n "$line" ]; do
        line=$(printf '%s' "$line" | tr -d '\r')
        trimmed=$(printf '%s' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

        case "$trimmed" in
            ''|\#*) continue ;;
        esac

        case "$trimmed" in
            \[*)
                section=$(printf '%s' "$trimmed" | sed 's/^\[\([^]]*\)\].*$/\1/')
                section=$(printf '%s' "$section" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

                if [ "$section" = "monitoring_ui" ]; then
                    in_section=1
                else
                    in_section=0
                fi
                continue
                ;;
        esac

        [ "$in_section" = "0" ] && continue

        case "$trimmed" in
            *=*)
                key=$(printf '%s' "$trimmed" | sed 's/^\([^=]*\)=.*/\1/')
                key=$(printf '%s' "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

                val=$(printf '%s' "$trimmed" | sed 's/^[^=]*=//')
                val=$(printf '%s' "$val" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                case "$val" in
                    *" #"*) val="${val%% #*}" ;;
                esac
                val=$(printf '%s' "$val" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                val=$(printf '%s' "$val" | sed "s/^['\"]//;s/['\"]$//")

                case "$key" in
                    username) WATCH_USER="$val" ;;
                    password) WATCH_PASS="$val" ;;
                esac
                ;;
        esac
    done < "$TOML_FILE"
fi

if [ -n "$WATCH_USER" ] && [ -n "$WATCH_PASS" ]; then
    log_msg "Fallback credentials loaded from [monitoring_ui]"
    HAS_CREDS=1
else
    log_msg "No fallback credentials in [monitoring_ui] (token-only mode)"
    HAS_CREDS=0
fi

# ============================================================
# [9] Check base64 availability
# ============================================================
# Needed only for the Basic Auth fallback path. Not required
# when the watchdog token is available.
# ============================================================
BASE64_CMD=""
if command -v base64 >/dev/null 2>&1; then
    BASE64_CMD="base64"
elif command -v busybox >/dev/null 2>&1 && busybox --list 2>/dev/null | grep -q "^base64$"; then
    BASE64_CMD="busybox base64"
fi

# ============================================================
# [10] Explicit safe PATH
# ============================================================
SAFE_PATH="/sbin:/system/bin:/system/xbin:/vendor/bin:/data/adb/magisk:/data/adb/ksu/bin:/data/adb/ap/bin"

# ============================================================
# [11] API call helper
# ============================================================
# Uses POST /api/ensure_running_service for CSRF-GET protection.
#
# Authentication (WD-TOKEN fix):
#   1. X-Watchdog-Token header  — preferred
#   2. Authorization: Basic ... — fallback (only when no token)
#
# Return codes:
#   0 — success (2xx)
#   1 — no HTTP client available
#   2 — network/timeout failure
#   3 — 429 rate-limited (curl path only)
#   4 — other HTTP error, OR unable to determine the result
#
# BUG-A fix: temp files live under $RUN_DIR, not /tmp.
# BUG-B fix: empty http_code returns 4, not 0.
# WD-TOKEN fix: X-Watchdog-Token header is sent when available.
# HARD-WD-01: all working variables declared `local`.
#
# M-4 fix: the wget/busybox paths no longer attempt to parse
# HTTP status from `-qO-` output (which never contains the
# headers). They rely on the process exit code instead. This
# is the ONLY reliable signal available when `curl` is absent.
# ============================================================
watchdog_api_call() {
    local action="$1"
    local tool=""
    local wd_token=""
    local token_header=""
    local auth_header=""
    local b64=""
    local url=""
    local http_code=""
    local exit_code=0
    local tmp_resp=""
    local tmp_code=""
    local output=""

    if command -v curl >/dev/null 2>&1; then
        tool="curl"
    elif command -v wget >/dev/null 2>&1; then
        tool="wget"
    elif command -v busybox >/dev/null 2>&1; then
        tool="busybox"
    else
        log_msg "WARNING: no HTTP client available"
        return 1
    fi

    # --- Build X-Watchdog-Token header (WD-TOKEN fix — preferred) ---
    # M-3 fix: the helper writes nothing to stderr, and its
    # failure mode is "empty stdout". `|| :` makes that
    # explicit and avoids the redundant `2>/dev/null` that
    # suppressed nothing.
    wd_token=$(_wd_get_watchdog_token 2>/dev/null || :)
    if [ -n "$wd_token" ]; then
        token_header="X-Watchdog-Token: $wd_token"
    fi

    # --- Build Authorization header (fallback) ---
    # Only used when no token is available. This preserves the
    # previous behavior for the edge case where main.go has not
    # yet written the token file (very early boot).
    if [ -z "$wd_token" ] && [ "$HAS_CREDS" = "1" ] && [ -n "$BASE64_CMD" ]; then
        b64=$(printf "%s:%s" "$WATCH_USER" "$WATCH_PASS" | $BASE64_CMD 2>/dev/null | tr -d '\n')
        if [ -n "$b64" ]; then
            auth_header="Authorization: Basic $b64"
        fi
    fi

    # --- URL ---
    url="http://127.0.0.1:$PORT/api/${action}_service"

    case "$tool" in
        curl)
            # BUG-A fix: temp files under $RUN_DIR, not /tmp.
            tmp_resp="${RUN_DIR}/.wd_resp.$$"
            tmp_code="${RUN_DIR}/.wd_code.$$"

            # Build the argument list incrementally so we can send
            # zero, one, or two auth headers as appropriate.
            if [ -n "$token_header" ] && [ -n "$auth_header" ]; then
                env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    curl -s --noproxy '*' --max-time 5 \
                    -o "$tmp_resp" -w '%{http_code}' \
                    -X POST \
                    -H "$token_header" \
                    -H "$auth_header" "$url" \
                    > "$tmp_code" 2>/dev/null
            elif [ -n "$token_header" ]; then
                env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    curl -s --noproxy '*' --max-time 5 \
                    -o "$tmp_resp" -w '%{http_code}' \
                    -X POST \
                    -H "$token_header" \
                    "$url" \
                    > "$tmp_code" 2>/dev/null
            elif [ -n "$auth_header" ]; then
                env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    curl -s --noproxy '*' --max-time 5 \
                    -o "$tmp_resp" -w '%{http_code}' \
                    -X POST \
                    -H "$auth_header" "$url" \
                    > "$tmp_code" 2>/dev/null
            else
                env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    curl -s --noproxy '*' --max-time 5 \
                    -o "$tmp_resp" -w '%{http_code}' \
                    -X POST \
                    "$url" \
                    > "$tmp_code" 2>/dev/null
            fi
            exit_code=$?

            if [ -f "$tmp_code" ]; then
                http_code=$(cat "$tmp_code" 2>/dev/null | tr -d '\r\n ')
            fi
            rm -f "$tmp_resp" "$tmp_code" 2>/dev/null

            # --- Analyze curl result ---
            if [ "$exit_code" -ne 0 ]; then
                log_msg "WARNING: API call failed (exit=$exit_code) — network/timeout"
                return 2
            fi

            if [ -n "$http_code" ]; then
                case "$http_code" in
                    200|201|202|204)
                        log_msg "API call succeeded (HTTP $http_code)"
                        return 0
                        ;;
                    429)
                        log_msg "API rate-limited (HTTP 429) — backing off"
                        return 3
                        ;;
                    *)
                        log_msg "WARNING: API call returned HTTP $http_code"
                        return 4
                        ;;
                esac
            fi

            # BUG-B fix: no http_code + exit_code=0 is UNDECIDABLE.
            # Treat as error so the watchdog retries with backoff.
            log_msg "WARNING: API call returned no HTTP status code (undecidable) — treating as error"
            return 4
            ;;

        wget)
            # M-4 fix: `wget -qO-` does NOT print HTTP headers,
            # so `http_code` is always empty here. Rely on the
            # exit code instead.
            #
            # GNU wget exit codes (relevant subset):
            #   0 — success (2xx)
            #   8 — server error (4xx/5xx)  → return 4
            #   * — network/timeout/parse   → return 2
            #
            # A 429 cannot be distinguished in this path and
            # will be treated as a generic failure, which is
            # acceptable (backoff applies either way).
            if [ -n "$token_header" ] && [ -n "$auth_header" ]; then
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    --header="$token_header" \
                    --header="$auth_header" "$url" \
                    2>&1) || exit_code=$?
            elif [ -n "$token_header" ]; then
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    --header="$token_header" "$url" \
                    2>&1) || exit_code=$?
            elif [ -n "$auth_header" ]; then
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    --header="$auth_header" "$url" \
                    2>&1) || exit_code=$?
            else
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    "$url" \
                    2>&1) || exit_code=$?
            fi

            if [ "$exit_code" -eq 0 ]; then
                log_msg "API call succeeded (wget exit 0)"
                return 0
            fi
            if [ "$exit_code" -eq 8 ]; then
                log_msg "WARNING: API call returned HTTP error (wget exit 8)"
                return 4
            fi
            log_msg "WARNING: API call failed (wget exit=$exit_code) — network/timeout"
            return 2
            ;;

        busybox)
            # M-4 fix: same rationale as the wget path above.
            # BusyBox wget returns 0 on success and 1 on most
            # errors; it does not provide granular exit codes.
            # Therefore any non-zero result is reported as a
            # generic HTTP error (return 4), which still drives
            # the backoff correctly.
            if [ -n "$token_header" ] && [ -n "$auth_header" ]; then
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    busybox wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    --header="$token_header" \
                    --header="$auth_header" "$url" \
                    2>&1) || exit_code=$?
            elif [ -n "$token_header" ]; then
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    busybox wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    --header="$token_header" "$url" \
                    2>&1) || exit_code=$?
            elif [ -n "$auth_header" ]; then
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    busybox wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    --header="$auth_header" "$url" \
                    2>&1) || exit_code=$?
            else
                output=$(env -i PATH="$SAFE_PATH" HOME=/data/local/tmp \
                    http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= \
                    no_proxy= NO_PROXY= \
                    busybox wget -qO- --no-proxy --timeout=5 --tries=1 \
                    --post-data='' \
                    "$url" \
                    2>&1) || exit_code=$?
            fi

            if [ "$exit_code" -eq 0 ]; then
                log_msg "API call succeeded (busybox wget exit 0)"
                return 0
            fi
            log_msg "WARNING: API call failed (busybox wget exit=$exit_code) — HTTP or network error"
            return 4
            ;;
    esac

    # Unreachable — all three branches above return explicitly.
    return 4
}

# ============================================================
# [12] Exponential backoff
# ============================================================
# WD-2 fix: the reset-on-STATUS_FILE-change applies ONLY to
# DNS_BACKOFF_CURRENT. The WebUI has no equivalent concept of
# "user intent" — its backoff resets only on a successful
# restart.
#
# HARD-WD-05: BACKOFF_BASE is used as the MINIMUM sleep
# interval, not as the sleep duration. See section [13.0].
# ============================================================
BACKOFF_BASE=30
BACKOFF_MAX=600

WEBUI_BACKOFF_CURRENT=30
DNS_BACKOFF_CURRENT=30

# --- Previous DNS intent (to detect STATUS_FILE changes) ---
PREV_DESIRED=""

# ============================================================
# [13] Main loop
# ============================================================
log_msg "Entering main loop..."
LOOP_COUNT=0

# --- HARD-WD-05: per-service last-attempt timestamps ---
# These track the epoch of the last attempt for each service.
# A service is only re-attempted when its own backoff has
# elapsed since its last attempt. This decouples the two
# services: while DNS is being backed off to 600s, the WebUI
# continues to be checked every 30s, and vice versa.
LAST_WEBUI_ATTEMPT=0
LAST_DNS_ATTEMPT=0

# WD-1 fix: the `{ ... } 2>/dev/null` wrapper was a no-op
# (log_msg writes to a file, not stderr) and has been removed.
_profile_hint=$(_wd_get_profile_memory_hint)
log_msg "Active profile: $_profile_hint"

while true; do
    LOOP_COUNT=$((LOOP_COUNT + 1))

    # --- [13.0] Compute sleep (HARD-WD-05) ---
    # Sleep for min(webui_backoff, dns_backoff), floored at a
    # small sanity value so we do not busy-wait. Each service
    # will only be *attempted* when its own backoff has elapsed
    # since the last attempt (see [13.2] / [13.3]).
    SLEEP_DURATION="$WEBUI_BACKOFF_CURRENT"
    if [ "$DNS_BACKOFF_CURRENT" -lt "$SLEEP_DURATION" ]; then
        SLEEP_DURATION="$DNS_BACKOFF_CURRENT"
    fi
    [ "$SLEEP_DURATION" -lt 5 ] && SLEEP_DURATION=5
    [ "$SLEEP_DURATION" -gt "$BACKOFF_MAX" ] && SLEEP_DURATION="$BACKOFF_MAX"

    sleep "$SLEEP_DURATION"

    # --- [13.1] Check for disable ---
    if [ -f "$MODDIR/disable" ]; then
        log_msg "module disabled -> Watchdog exiting"
        rm -f "$WATCHDOG_PID_FILE" 2>/dev/null
        exit 0
    fi

    # HARD-WD-06: guard against empty `date` output.
    now=$(date +%s 2>/dev/null)
    case "$now" in
        ''|*[!0-9]*) now=0 ;;
    esac

    # ============================================================
    # [13.2] Restart WebUI
    # ============================================================
    # Only attempt when WEBUI_BACKOFF_CURRENT has elapsed since
    # LAST_WEBUI_ATTEMPT.
    #
    # M-2 fix: `_wd_cleanup_webui` is called exactly ONCE, here,
    # immediately before the start attempt. It is no longer
    # duplicated inside `_wd_start_webui`.
    if [ "$AUTO_RESTART_WEBUI" = "1" ]; then
        if [ $((now - LAST_WEBUI_ATTEMPT)) -ge "$WEBUI_BACKOFF_CURRENT" ]; then
            LAST_WEBUI_ATTEMPT="$now"

            if ! _wd_is_port_open "$PORT" tcp; then
                log_msg "WebUI down on port $PORT — restarting..."
                _wd_cleanup_webui
                sleep 1

                if _wd_start_webui "$WEBUI" "$PORT"; then
                    WEBUI_BACKOFF_CURRENT="$BACKOFF_BASE"
                else
                    WEBUI_BACKOFF_CURRENT=$((WEBUI_BACKOFF_CURRENT * 2))
                    [ "$WEBUI_BACKOFF_CURRENT" -gt "$BACKOFF_MAX" ] && WEBUI_BACKOFF_CURRENT="$BACKOFF_MAX"
                    log_msg "WARNING: WebUI restart failed — next attempt in ${WEBUI_BACKOFF_CURRENT}s"
                fi
            else
                # WebUI is running — reset backoff
                WEBUI_BACKOFF_CURRENT="$BACKOFF_BASE"
            fi
        fi
    fi

    # ============================================================
    # [13.3] Restart DNS Engine
    # ============================================================
    #
    # STATUS_FILE represents "user intent":
    #   * ON  = user wants the service running -> Watchdog restarts it
    #   * OFF = user stopped it manually -> Watchdog does nothing
    #
    # DNS_BACKOFF is independent from WEBUI_BACKOFF.
    # DNS backoff resets when STATUS_FILE changes (user changed
    # intent) — this is the only place STATUS_FILE affects backoff.
    #
    # Only attempt when DNS_BACKOFF_CURRENT has elapsed since
    # LAST_DNS_ATTEMPT.
    if [ "$AUTO_RESTART_DNS" = "1" ]; then
        desired="OFF"
        if [ -f "$STATUS_FILE" ]; then
            desired=$(cat "$STATUS_FILE" 2>/dev/null | tr -d '\r\n ')
        fi
        [ -z "$desired" ] && desired="OFF"

        # --- Detect intent change -> reset backoff ---
        if [ "$desired" != "$PREV_DESIRED" ]; then
            if [ -n "$PREV_DESIRED" ]; then
                log_msg "STATUS_FILE changed: $PREV_DESIRED -> $desired"
            fi
            PREV_DESIRED="$desired"
            DNS_BACKOFF_CURRENT="$BACKOFF_BASE"
        fi

        if [ "$desired" = "ON" ]; then
            if [ $((now - LAST_DNS_ATTEMPT)) -ge "$DNS_BACKOFF_CURRENT" ]; then
                LAST_DNS_ATTEMPT="$now"

                if ! _wd_is_port_open 5354 udp; then
                    # Wait a moment + re-check (it may have just started)
                    sleep 1
                    recheck="OFF"
                    if [ -f "$STATUS_FILE" ]; then
                        recheck=$(cat "$STATUS_FILE" 2>/dev/null | tr -d '\r\n ')
                    fi

                    if [ "$recheck" != "ON" ]; then
                        log_msg "status changed to $recheck during check — skipping restart"
                        PREV_DESIRED="$recheck"
                        DNS_BACKOFF_CURRENT="$BACKOFF_BASE"
                    else
                        log_msg "DNS Engine down (5354/UDP) — calling ensure_running..."

                        watchdog_api_call "ensure_running"
                        RC=$?

                        case "$RC" in
                            0)
                                log_msg "DNS restart succeeded"
                                DNS_BACKOFF_CURRENT="$BACKOFF_BASE"
                                ;;
                            3)
                                # rate-limited — extra backoff
                                DNS_BACKOFF_CURRENT=$((DNS_BACKOFF_CURRENT * 2))
                                [ "$DNS_BACKOFF_CURRENT" -gt "$BACKOFF_MAX" ] && DNS_BACKOFF_CURRENT="$BACKOFF_MAX"
                                log_msg "WARNING: rate-limited — next attempt in ${DNS_BACKOFF_CURRENT}s"
                                ;;
                            *)
                                DNS_BACKOFF_CURRENT=$((DNS_BACKOFF_CURRENT * 2))
                                [ "$DNS_BACKOFF_CURRENT" -gt "$BACKOFF_MAX" ] && DNS_BACKOFF_CURRENT="$BACKOFF_MAX"
                                log_msg "WARNING: DNS restart failed (rc=$RC) — next attempt in ${DNS_BACKOFF_CURRENT}s"
                                ;;
                        esac
                    fi
                else
                    # DNS is running — reset backoff
                    DNS_BACKOFF_CURRENT="$BACKOFF_BASE"
                fi
            fi
        fi
    fi

    # --- [13.4] Periodic log every 20 iterations (~10 minutes) ---
    if [ $((LOOP_COUNT % 20)) -eq 0 ]; then
        log_msg "Watchdog alive (loop #$LOOP_COUNT, webui_backoff=${WEBUI_BACKOFF_CURRENT}s, dns_backoff=${DNS_BACKOFF_CURRENT}s)"
    fi
done

# Unreachable (infinite loop)
exit 0